const Router = require('express')
const router = new Router()
const branchRouter = require('./branchRouter')
const courseRouter = require('./courseRouter')
const curatorRouter = require('./curatorRouter')
const eventRouter = require('./eventRouter')
const eventTypeRouter = require('./eventTypeRouter')
const forWhomCourseRouter = require('./forWhomCourseRouter')
const forWhomEventRouter = require('./forWhomEventRouter')
const lessonRouter = require('./lessonRouter')
const themeRouter = require('./themeRouter')
const willLearnRouter = require('./willLearnRouter')
const blogRouter = require('./blogRouter')
const blogTypeRouter = require('./blogTypeRouter')
const articleElementRouter = require('./articleElementRouter')
const videoElementRouter = require('./videoElementRouter')
const podcastElementRouter = require("./podcastElementRouter")
const tagRouter = require('./tagRouter')
const articleElementListRouter = require('./articleElementListRouter')
const emailSendRouter = require("./emailSendRouter")

router.use("/course", courseRouter)
router.use("/curator", curatorRouter)
router.use("/event", eventRouter)
router.use("/branch", branchRouter)
router.use("/eventType", eventTypeRouter)
router.use("/forWhomCourse", forWhomCourseRouter)
router.use("/forWhomEvent", forWhomEventRouter)
router.use("/lesson", lessonRouter)
router.use("/theme", themeRouter)
router.use("/willLearn", willLearnRouter)
router.use("/blog", blogRouter)
router.use("/blogType", blogTypeRouter)
router.use("/articleElement", articleElementRouter)
router.use("/videoElement", videoElementRouter)
router.use("/podcastElement", podcastElementRouter)
router.use("/tag", tagRouter)
router.use("/articleElementList", articleElementListRouter)
router.use("/email", emailSendRouter)


module.exports = router